task: CognitiveRL-Nav-v2
env_cfg_entry_point: env_cfg_entry_point
num_envs: 64
seed: 1
capture_video: false
video: false
video_length: 200
video_interval: 2000
disable_fabric: false
distributed: false
headless: true
enable_cameras: true
exp_name: td3_continuous_action
torch_deterministic: true
device: cuda:0
total_timesteps: 1000000
learning_rate: 0.0003
buffer_size: 25000
gamma: 0.99
tau: 0.005
batch_size: 256
policy_noise: 0.2
exploration_noise: 0.1
learning_starts: 25000
policy_frequency: 2
noise_clip: 0.5
measure_burnin: 3
agent_type: CNNTD3Agent
checkpoint_interval: 10000
play_interval: 10000
run_play: false
render_play: false
render_best: false
num_eval_episodes: 1 